{
 "title": "Banka Analiz",
 "time": { "from": "now/y", "to": "now" },
 "panels": [
  {
   "title": "Alacak",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select\r\n\tcast(DATEDIFF(SECOND,{d '1970-01-01'}, getdate()) as int) as time, \r\n\tSUM(ALACAK) as alacak\r\n--\tSUM(BAKIYE) as bakiye\r\n--\tSUM(BORC) as borc \r\nfrom \r\n\tBooBoo.dbo.Banka"
    }
   ]
  },
  {
   "title": "Borç",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select\r\n\tcast(DATEDIFF(SECOND,{d '1970-01-01'}, getdate()) as int) as time, \r\n--\tSUM(ALACAK) as alacak\r\n--\tSUM(BAKIYE) as bakiye\r\n\tSUM(BORC) as borc \r\nfrom \r\n\tBooBoo.dbo.Banka"
    }
   ]
  },
  {
   "title": "Bakiye",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select\r\n\tcast(DATEDIFF(SECOND,{d '1970-01-01'}, getdate()) as int) as time, \r\n--\tSUM(ALACAK) as alacak,\r\n\tSUM(BAKIYE) as bakiye\r\n--\tSUM(BORC) as borc \r\nfrom \r\n\tBooBoo.dbo.Banka"
    }
   ]
  },
  {
   "title": "Şube Sayısı",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select  count( DISTINCT ISYERI) as subesayisi from  BooBoo.dbo.banka "
    }
   ]
  },
  {
   "title": "Çalışılan Banka Sayısı",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select  count( DISTINCT BANKA_ADI) as calisilanbanka from  BooBoo.dbo.banka"
    }
   ]
  },
  {
   "title": "Banka Hesap Adedi",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select  count( DISTINCT BANKA_HESAP_ADI) as calisilanhesap from  BooBoo.dbo.banka "
    }
   ]
  },
  {
   "title": "Bankalar",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "select \r\n\t--cast(DATEDIFF(SECOND,{d '1970-01-01'}, getdate()) as int) as time,\r\n\tBANKA_ADI,SUM(BAKIYE) as bakiye,SUM(BAKIYE)/(select SUM(BAKIYE) from BooBoo.dbo.Banka)*100 as bakiyepercent \r\nfrom \r\n\tBooBoo.dbo.Banka\r\ngroup by \r\n\tBANKA_ADI"
    }
   ]
  },
  {
   "title": "Banka Durumu",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\r\n \r\n\tcast(DATEDIFF(SECOND,{d '1970-01-01'}, TARIH) as int) as time,\r\n\tSUM(BAKIYE) as bakiye ,\r\n\tBANKA_ADI\r\nfrom \r\n\t BooBoo.dbo.Banka\r\ngroup by \r\n\tTARIH,BANKA_ADI\r\n"
    }
   ]
  },
  {
   "title": "Banka Hesap Hareketleri",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select \r\n\tcast(DATEDIFF(SECOND,{d '1970-01-01'}, TARIH) as int) as time,\r\n\tISLEM_TURU,\r\n\tSUM(BAKIYE) as tutar \r\nfrom \r\n\tBooBoo.dbo.Banka\r\ngroup by \r\n\tISLEM_TURU,cast(DATEDIFF(SECOND,{d '1970-01-01'}, TARIH) as int)"
    }
   ]
  },
  {
   "title": "Top 10 Alacak",
   "type": "michaeldmoore-multistat-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "\r\n select top 10  CH_UNVANI as unvan ,SUM(Alacak) as alacaktutari,count(1) as alacakadedi from BooBoo.dbo.banka\r\n group by CH_UNVANI\r\n order by 2 desc\r\n\r\n "
    }
   ]
  },
  {
   "title": "Dövize Göre Dağılım",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "select \r\n\tcast(DATEDIFF(SECOND,{d '1970-01-01'}, getdate()) as int) as time,\r\n\tISLEM_DOVIZ_TURU,SUM(ISLEM_DOVIZ_TUTARI) as tutar \r\nfrom \r\n\tBooBoo.dbo.Banka\r\ngroup by \r\n\tISLEM_DOVIZ_TURU\r\n"
    }
   ]
  },
  {
   "title": "İşlemlere Göre Banka Döviz Kurları",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n\t$__timeEpoch(TARIH),\n\tISLEM_DOVIZ_TURU,\n\tISLEM_DOVIZ_KURU\nFROM \n\t BooBoo.dbo.banka\nwhere \n\tISLEM_DOVIZ_TURU <>'TL'\ngroup by \n\tTARIH,ISLEM_DOVIZ_TURU,ISLEM_DOVIZ_KURU\nORDER BY TARIH"
    }
   ]
  }
 ]
}