{
 "title": "Firma",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Firma Sayısı",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(1) from [BooBoo].[CRM].[Firma]"
    }
   ]
  },
  {
   "title": "Satışlarda Kullanılabilir",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(1) from [BooBoo].[CRM].[Firma] f\r\nINNER JOIN [BooBoo].[CRM].[FirmaRoles] fr ON f.FirmRole=fr.Oid\r\nwhere fr.[CanUseInSales]=1"
    }
   ]
  },
  {
   "title": "Oran",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 5, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select 100.0*count(1)/(select count(1) from [BooBoo].[CRM].[Firma]) from [BooBoo].[CRM].[Firma] f\r\nINNER JOIN [BooBoo].[CRM].[FirmaRoles] fr ON f.FirmRole=fr.Oid\r\nwhere fr.[CanUseInSales]=1"
    }
   ]
  },
  {
   "title": "Referans Kaynağı",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": " select DATEDIFF(SECOND,{d '1970-01-01'}, getdate()) as time, ISNULL(cast([ReferenceSource] as nvarchar(max)),'N/A') as ReferansKaynagi,count(1) FROM  [BooBoo].[CRM].[Firma] f\r\n group by [ReferenceSource]\r\n"
    }
   ]
  },
  {
   "title": "Bolgedeki Firmalar",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "\r\n select DATEDIFF(SECOND,{d '1970-01-01'}, getdate()) as time, ISNULL(sb.[AreaName],'N/A'),count(1) as firmaSayisi from [BooBoo].[CRM].[Firma] f\r\n LEFT JOIN [BooBoo].[CRM].[SatisPersonel] sp ON f.SalesRep=sp.oid\r\n LEFT JOIN [BooBoo].[CRM].[SatisBolge] sb ON sp.SalesArea=sb.[Oid]\r\n group by sb.[AreaName]"
    }
   ]
  },
  {
   "title": "Satış Temsilcisi",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "  select DATEDIFF(SECOND,{d '1970-01-01'}, getdate()) as time, ISNULL(REPLACE(CONCAT(sp.FirstName,' ', sp.MiddleName,' ',sp.LastName),'  ',' '),'N/A') as AdSoyad,count(1) as firmaSayisi from [BooBoo].[CRM].[Firma] f\r\n LEFT JOIN [BooBoo].[CRM].[SatisPersonel] sp ON f.SalesRep=sp.oid\r\n group by FirstName, MiddleName,LastName"
    }
   ]
  },
  {
   "title": "Firma Sektör",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": " select DATEDIFF(SECOND,{d '1970-01-01'}, getdate()) as time, ISNULL(fs.[SectorName],'N/A')  ,count(1) from [BooBoo].[CRM].[Firma] f\r\n LEFT JOIN [BooBoo].[CRM].[FirmaSektor] fs ON f.MainSector=fs.[Oid]\r\n group by fs.[SectorName] \r\n"
    }
   ]
  },
  {
   "title": "Firma Rolü",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": " select DATEDIFF(SECOND,{d '1970-01-01'}, getdate()) as time,ISNULL(fr.RoleName,'N/A'),count(1) from [BooBoo].[CRM].[Firma] f\r\nLEFT JOIN [BooBoo].[CRM].[FirmaRoles] fr ON f.FirmRole=fr.Oid\r\ngroup by fr.RoleName"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT        FirmCode, FirmTitle, RoleName, SectorName, ReferenceSource, FirstName+' '+LastName, \r\n                         CityOfMainAddress, CountryOfMainAddress, EmailAddress1, EmailAddress2, FirmCategory01, Phones\r\nFROM            [BooBoo].[CRM].[Firma] f\r\n\t\t\t\tLEFT OUTER JOIN [BooBoo].[CRM].SatisPersonel sp ON f.SalesRep = sp.oid \r\n\t\t\t\tLEFT OUTER JOIN [BooBoo].[CRM].FirmaSektor fs ON f.MainSector = fs.Oid \r\n\t\t\t\tLEFT OUTER JOIN [BooBoo].[CRM].FirmaRoles fr ON f.FirmRole = fr.Oid"
    }
   ]
  }
 ]
}