{
 "title": "Teklif",
 "time": { "from": "now-2y", "to": "now" },
 "panels": [
  {
   "title": "Teklif Sayısı",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(1) FROM [BooBoo].[CRM].[Teklif]"
    }
   ]
  },
  {
   "title": "Aktif Satış Personeli",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(1) as aktifSatisPersoneli\r\n  FROM [BooBoo].[CRM].[SatisPersonel]\r\n  where IsActive=1"
    }
   ]
  },
  {
   "title": "Teklif Tür",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "\tselect DATEDIFF(SECOND,{d '1970-01-01'}, GETDATE()) as time, \r\n  ISNULL(cast(ProposalType as varchar(50)),'N/A') as TeklifTur, count(1) as adet FROM [BooBoo].[CRM].[Teklif]\r\n  group by ProposalType"
    }
   ]
  },
  {
   "title": "Satış Temsilcisi",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT \r\n\tDATEDIFF(SECOND,{d '1970-01-01'}, getdate()) as time, \r\n    REPLACE(CONCAT(td.FirstName,' ', td.MiddleName,' ',td.LastName),'  ',' ') as AdSoyad,\r\n    count(1) as adet\r\nFROM [BooBoo].[CRM].[Teklif] t\r\nINNER JOIN [BooBoo].[CRM].[SatisPersonel] td ON t.[SalesRep]= td.oid\r\nwhere [IsActive]=1\r\ngroup by td.FirstName, td.MiddleName,td.LastName"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \r\n\tDATEDIFF(SECOND,{d '1970-01-01'}, getdate()) as time, \r\n    td.[TeklifDurum],\r\n\t\r\n    count(1) as adet\r\nFROM [BooBoo].[CRM].[Teklif] t\r\nINNER JOIN [BooBoo].CRM.TeklifDurum td ON t.ProposalState= td.ProposalState\r\ngroup by td.[TeklifDurum]"
    }
   ]
  },
  {
   "title": "Teklif Durumları",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT \r\n\tDATEDIFF(SECOND,{d '1970-01-01'}, getdate()) as time, \r\n    td.[TeklifDurum]\r\n    ,count(1) as adet\r\nFROM [BooBoo].[CRM].[Teklif] t\r\nINNER JOIN [BooBoo].CRM.TeklifDurum td ON t.ProposalState= td.ProposalState\r\ngroup by td.[TeklifDurum]"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "/****** Script for SelectTopNRows command from SSMS  ******/\r\nSELECT  \r\n[ProposalId] as TeklifId\r\n,[ProposalStartDate] as TeklifTarihi\r\n,[ProposalDescription] as TeklifTanim\r\n,ISNULL(cast([ProposalType] as varchar(50)),'N/A') as TeklifTur\r\n,[Total_LC_GrandTotal]\r\n,tf.PercentComplete\r\n,tf.StageDescription\r\n,td.TeklifDurum\r\n,ton.[Oncelik]\r\n  FROM [BooBoo].[CRM].[Teklif] t\r\n  INNER JOIN [BooBoo].[CRM].[TeklifFaz] tf ON t.[ProposalStage]=tf.Oid\r\n  INNER JOIN [BooBoo].[CRM].[TeklifDurum] td ON t.[ProposalState]=td.ProposalState\r\n  INNER JOIN [BooBoo].[CRM].[TeklifOncelik] ton ON t.Priority=ton.[ProposalPriority]\r\norder by 2 desc"
    }
   ]
  },
  {
   "title": "Aylık Toplam Teklif",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \r\n     cast(DATEDIFF(SECOND,{d '1970-01-01'}, DATEADD(MONTH, DATEDIFF(MONTH, 0, [ProposalStartDate]), 0)) as int) as time,\r\n      SUM([Total_LC_GrandTotal]) as TeklifToplam\r\n  FROM [BooBoo].[CRM].[Teklif]\r\n  group by DATEADD(MONTH, DATEDIFF(MONTH, 0, [ProposalStartDate]), 0) "
    }
   ]
  }
 ]
}