{
 "title": "Temsilci",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "tem",
    "label": "tem",
    "query": "select DISTINCT [SATIS_ELEMANI_ADI] FROM DEMET"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeEpoch(<time_column>),\n  <value column> as value,\n  <series name column> as metric\nFROM\n  <table name>\nWHERE\n  $__timeFilter(time_column)\nORDER BY\n  <time_column> ASC"
    }
   ]
  },
  {
   "title": "dtay",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select CARI_HESAP_ADI,SUM(TUTAR) as val from dbo.DEMET \r\nwhere \r\n1=1\r\nAND ((LEN(CONCAT($tem,''))=0) OR SATIS_ELEMANI_ADI IN ($tem))\r\ngroup by CARI_HESAP_ADI\r\norder by 2 desc"
    }
   ]
  },
  {
   "title": "toplam",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select SUM(TUTAR) from dbo.DEMET "
    }
   ]
  },
  {
   "title": "Satış Temsilcisi",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select $__unixEpochTo() AS time,[SATIS_ELEMANI_ADI],SUM(TUTAR) from dbo.DEMET \r\nwhere \r\n1=1\r\nAND ((LEN(CONCAT($tem,''))=0) OR SATIS_ELEMANI_ADI IN ($tem))\r\ngroup by [SATIS_ELEMANI_ADI]"
    }
   ]
  }
 ]
}